version: '3.9'

services:
  nginx:
    container_name: nginx
    image: nginx:1.13
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d

  angular:
    container_name: angular
    build: ./angularclient
    restart: always
    ports:
      - 4200:4200
    depends_on:
      - springboot

  mysql:
    container_name: mysql
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_DATABASE: tabledb
      MYSQL_ROOT_PASSWORD: Formation123
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    restart: always

  springboot:
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tabledb?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Formation123
    build:
      context: ./projethn
      dockerfile: Dockerfile
    working_dir: /springboot
    volumes:
      - ./projethn:/springboot
      - ~/.m2:/root/.m2
    expose:
      - "8080"
    depends_on:
      - nginx
      - mysql
    command: mvn clean spring-boot:run -Dspring-boot.run.profiles=docker